import "../globals.css";
import type { Metadata } from "next";
import { useLocale } from "next-intl";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const locale = useLocale();

	if (params.locale !== locale) {
		notFound();
	}

	return (
		<html lang={locale}>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
